######################################################################
# Automatically generated by qmake (3.0) Mon Dec 7 13:51:24 2015
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = a4
INCLUDEPATH += .

# Input
HEADERS += algebra.h polyroots.h
SOURCES += algebra.cpp main.cpp polyroots.cpp
